// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALzMhlgTp9LkicNAp0vbB-58MT62mXnxM',
    appId: '1:734359558907:web:e754032174c21d5d706e5e',
    messagingSenderId: '734359558907',
    projectId: 'focus-todo-app-cefe6',
    authDomain: 'focus-todo-app-cefe6.firebaseapp.com',
    storageBucket: 'focus-todo-app-cefe6.firebasestorage.app',
    measurementId: 'G-FXWYVX6K4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZLKFcRKinAcxynTn3Ygi89wu1N6K67w',
    appId: '1:734359558907:android:1a931a3f087be752706e5e',
    messagingSenderId: '734359558907',
    projectId: 'focus-todo-app-cefe6',
    storageBucket: 'focus-todo-app-cefe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM1phIq4HD1xc0dzBzFnnuqQdlg9vqEo4',
    appId: '1:734359558907:ios:e93e7ddaba1ca463706e5e',
    messagingSenderId: '734359558907',
    projectId: 'focus-todo-app-cefe6',
    storageBucket: 'focus-todo-app-cefe6.firebasestorage.app',
    iosClientId: '734359558907-peiugg6m3dtgfmahk0gln6204b26ii7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM1phIq4HD1xc0dzBzFnnuqQdlg9vqEo4',
    appId: '1:734359558907:ios:e93e7ddaba1ca463706e5e',
    messagingSenderId: '734359558907',
    projectId: 'focus-todo-app-cefe6',
    storageBucket: 'focus-todo-app-cefe6.firebasestorage.app',
    iosClientId: '734359558907-peiugg6m3dtgfmahk0gln6204b26ii7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALzMhlgTp9LkicNAp0vbB-58MT62mXnxM',
    appId: '1:734359558907:web:bcb6966309ac28de706e5e',
    messagingSenderId: '734359558907',
    projectId: 'focus-todo-app-cefe6',
    authDomain: 'focus-todo-app-cefe6.firebaseapp.com',
    storageBucket: 'focus-todo-app-cefe6.firebasestorage.app',
    measurementId: 'G-3C7MK3X02J',
  );
}
